/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
	aws_project_region: "ap-south-1",
	aws_cognito_identity_pool_id:
		"ap-south-1:82de00f1-0a00-4aba-8166-db817ae547ac",
	aws_cognito_region: "ap-south-1",
	aws_user_pools_id: "ap-south-1_Gk24brDHd",
	aws_user_pools_web_client_id: "1ienqhj86ljjncv79no53impj5",
	oauth: {},
	aws_cognito_username_attributes: ["EMAIL"],
	aws_cognito_social_providers: [],
	aws_cognito_signup_attributes: ["EMAIL"],
	aws_cognito_mfa_configuration: "OFF",
	aws_cognito_mfa_types: ["SMS"],
	aws_cognito_password_protection_settings: {
		passwordPolicyMinLength: 8,
		passwordPolicyCharacters: [],
	},
	aws_cognito_verification_mechanisms: ["EMAIL"],
};

export default awsmobile;
